#!/usr/bin/env bash

function f_yum_install_httpd(){
  sleep 3
  #ssh -i ~/.ssh/${v_key_name}.pem -o "StrictHostKeyChecking no" ec2-user@`f_get_instance_public_dns $(f_get_instance_id)` sudo yum update >> /dev/null
  ssh -i ~/.ssh/${v_key_name}.pem -o "StrictHostKeyChecking no" ec2-user@`f_get_instance_public_dns $(f_get_instance_id)` sudo yum -y install httpd >> /dev/null
}

function f_create_index_html(){
  ssh -i ~/.ssh/${v_key_name}.pem -o "StrictHostKeyChecking no" ec2-user@`f_get_instance_public_dns $(f_get_instance_id)` sudo tee /var/www/html/index.html < ${_srcDir}/files/index.html >> /dev/null
  ssh -i ~/.ssh/${v_key_name}.pem -o "StrictHostKeyChecking no" ec2-user@`f_get_instance_public_dns $(f_get_instance_id)` sudo chown apache -R /var/www/html >> /dev/null
}

function f_enable_start_httpd(){
  ssh -i ~/.ssh/${v_key_name}.pem -o "StrictHostKeyChecking no" ec2-user@`f_get_instance_public_dns $(f_get_instance_id)` sudo service httpd start >> /dev/null
  ssh -i ~/.ssh/${v_key_name}.pem -o "StrictHostKeyChecking no" ec2-user@`f_get_instance_public_dns $(f_get_instance_id)` sudo chkconfig httpd on >> /dev/null
}
