#!/usr/bin/env bash

function f_cleanup(){
  # The following steps will restore back to a clean environment
  echo -e "\t\tDeleting key pair..."
  f_delete_key_pair
  echo -e "\t\tTerminating instances..."
  #f_terminate_instances
  #echo -e "\t\t\tWaiting for instances to terminate..."
  #f_verify_instance_terminated
  #echo -e "\t\tDeregister AMI..."
  f_deregister_image
  echo -e "\t\t\tDeleting AMI snapshot..."
  f_delete_snapshots
  echo -e "\t\tDeleting ELB..."
  f_delete_elb
  echo -e "\t\tDeleting CloudWatch alarms..."
  f_delete_cloudwatch_alarms "${v_cloudwatch_alarm_name_scaleout} ${v_cloudwatch_alarm_name_scalein}"
  echo -e "\t\tDeleting Autoscale policies..."
  f_delete_autoscaler_policy "${v_autoscaler_policy_name_scaleout}"
  f_delete_autoscaler_policy "${v_autoscaler_policy_name_scalein}"
  echo -e "\t\tDeleting Autoscaler..."
  f_delete_autoscaler_group
  f_delete_autoscaler_config
  echo -e "\t\tDeleting security group..."
  f_delete_security_group
  rm -f ${_srcDir}/cache/*
}
